<a href="https://colab.research.google.com/github/ram345345/ML_23AG1A66E6/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
list1 = [2, 4, 6, 8]
array1 = np.array(list1)

print(array1)



[2 4 6 8]


In [13]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)


[2 4 6 8]


In [12]:
#2D array
array2= np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array2)


[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#3D array
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [7]:
# data type of array1

array1 = np.array([2, 4, 6])
print(array1.dtype)


int64


In [17]:
#2D array data type
array2= np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array2.dtype)


int64


In [18]:
#3D array data type
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array3.dtype)

int64


In [24]:
#dimension in array3
print(array3.ndim)

3


In [15]:
#dimension in array2
print(array2.ndim)

2


In [16]:
#dimension in array1
print(array1.ndim)

1


In [19]:
#2D array
array2= np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array2.shape)


(2, 4)


In [20]:
#3D array data type
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array3.shape)

(2, 3, 4)


In [21]:
#item size of the array4
array4 = np.array([6, 7, 8, 10, 13])
print(array4.itemsize)


8


In [23]:
#item size of the array5
array5 = np.array([6, 7, 8, 10, 13],dtype=np.int32)
print(array5.itemsize)


4


In [25]:
#data location of the array6 &array7
array6 = np.array([6, 7, 8])
array7 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])
print("data of array6:",array6.data)
print("data of array7:",array7.data)


data of array6: <memory at 0x7887660c5180>
data of array7: <memory at 0x7887660e65a0>


In [31]:
#array modifying
array1[1]=10
print(array1)

[ 2 10  6  8]
